### ISSUE TITLE
[code review] todos and doubts

### ISSUE THREAD

**Issue by devAbnull** [palash0109/Sprinklr-App-Starter-kit#1]
### Todos
- [x] support for `help(-h)` option to list available options' doc
- [x] remove unnecessary occurrences of `console.log` ([ref](https://github.com/palash0109/Sprinklr-App-Starter-kit/blob/main/createSprApp.js#L94))
- [x] create `templates/*` directory to add standard templates
  - [x]  keep `src/*` as default template
  - [x] add default `template.json` in default template
- [ ] save devDependencies in `package.json` //spawn sync
- [x] make createSprApp dir instead of file, and move `helper/*` in createSprApp dir
- [x] _needs discussion_: template and default template configs are merged in 3 different places, deps are merged in `install()`, scripts and other package.json keys are merged in `merge()`, webpack is merged in `webpack.config.js`
  - [x] _suggestion_: let `merge()` do all the merging of scripts and dependencies outputs package.json with deps, `install()` only installs packages.
  - [x] `spr.config.js` <> `webpack.custom.config.js`, default webpack config in `webpack.base.config.js`, and `webpack.config.js` will just merge above configs

### Doubts
- [x] when will be `options.template` be `true` ([ref](https://github.com/palash0109/Sprinklr-App-Starter-kit/blob/main/createSprApp.js#L39))
- [x] need example for `spr.config.js` 
- [x] what's difference between template.json and spr.config.js? if spr.config.js contains only custom webpack.config then can we call it webpack.template.config.js ?
